### ISSUE TITLE
Speed up loading

### ISSUE THREAD

**Issue by stefan-balke** [hajicj/muscima#14]
Hey,

in our data loader for `msmd` we found that the function `decode_mask_rle()` takes most of the time when loading a mung (cf. screenshot from the profiler below).

I guess it is due to the reshaping: https://github.com/hajicj/muscima/blob/098cc9a3177d02aaf3a57bfd642645ff0b948571/muscima/cropobject.py#L1031
Since you know the desired shapes in that function, are there any chances to speed this up by using some memory allocation or using a different way reshaping or getting rid of it by defining the desired shape in advance and fill an `np.ndarray` directly?

Thank you!

![screen_shot_2019-03-06_at_14 36 03](https://user-images.githubusercontent.com/7326732/53946536-51b38d00-40c4-11e9-923c-f772270f19f9.png)

**Comment by apacha** [comment]
The biggest issue does not seem to be the reshaping, but the creation of the numpy-array. I've [profiled the method](https://github.com/OMR-Research/mung/commit/62eb570019802a37d7704156ef3dfe5f4b521cdb) and implemented an improvement, which significantly cuts the runtime to about 1/3 of the original runtime.

The new bottleneck is splitting the strings - a task that unfortunately cannot be sped up. If you still have performance issues, consider caching the masks, as they are quite small, they can easily be stored in memory.
![2019-08-12 17_05_39-Window](https://user-images.githubusercontent.com/594497/62875573-8c7cb980-bd23-11e9-807c-390a10dab439.png)

Unfortunately, this fix will not be implemented into the `muscima` package, as it is deprecated an no longer actively maintained. However, the improvement is implemented in the [`mung`](https://github.com/OMR-Research/mung) package which is the successor, which was recently released and has been updated to accommodate MUSCIMA++ v2.0. If you are interested in this fix, you should consider transitioning to that package. (Keep in mind, that this will need some migration effort, as classes have been renamed, e.g., CropObject -> Node).
