### ISSUE TITLE
Refactor crop-object class names

### ISSUE THREAD

**Issue by apacha** [hajicj/muscima#4]
**Problem:** Some class names currently contain special characters, that are not ideal when being used.

**Comment by hajicj** [comment]
The class names should perhaps follow the [SMuFL](https://www.smufl.org/) specification?

**Comment by apacha** [comment]
Good idea! But before we actually decide, we should also consult the [MusicXML](http://www.musicxml.com/for-developers/) and [MEI](http://music-encoding.org/downloads/latest-release/) specification. Maybe they though of something that we don't want to miss.

**Comment by hajicj** [comment]
It seems they thought of the same thing:

[Verovio](http://music-encoding.org/tools/verovio/) page says: "Verovio follows the Standard Music Font Layout (SMuFL) specification and the font can be changed for personalizing the output."

**Comment by apacha** [comment]
Check out the main contributor: https://github.com/rism-ch/verovio/graphs/contributors
:-)

**Comment by apacha** [comment]
See https://docs.google.com/spreadsheets/d/1jF3s_AwFmLPkkHb-f6g36AO_eMrIp6NNwVijDAV0w8Q/edit?usp=sharing and https://github.com/OMR-Research/muscima-pp/issues/2

**Comment by apacha** [comment]
Solved in https://github.com/OMR-Research/mung.
